name: 'Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project'

on:
  push:
    branches: [main, dev]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build

  deploy:
        needs: test-build
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [20.x]
        steps:
        - name:  Build app on VM
          uses: appleboy/ssh-action@master
          with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              script: |
                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/vm_senpro_modul2_23
                  echo "Cek Folder Project";
                  [ ! -d "${HOME}/senpro/477892/modul02/senpro-github-action/" ] &&
                  {
                      echo "Repository belum di-clone. Cloning...";
                      mkdir -p ~/senpro/477892/modul02;
                      cd ~/senpro/477892/modul02;
                      git clone https://github.com/mastamaru/senpro-github-action
                  } || {
                      echo "Repository sudah ada. Building...";
                      cd ~/senpro/477892/modul02/senpro-github-action;
                      git restore .;
                      git pull origin main;
                  }